# Generated by Django 5.0.1 on 2024-02-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_item_version_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='version',
        ),
        migrations.AddField(
            model_name='item',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
