# Generated by Django 5.0.1 on 2024-02-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_buyer_solditem_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solditem',
            name='sale_date',
        ),
    ]
