# Item list

ITEM_LIST = [
    {"title": "necklace", "description": "elegant silver design", "price": 49.99},
    {"title": "bag", "description": "leather messenger", "price": 79.99},
    {"title": "watch", "description": "analog timepiece", "price": 99.99},
    {"title": "mugs", "description": "handcrafted ceramic set", "price": 29.99},
    {"title": "earbuds", "description": "bluetooth wireless", "price": 59.99},
    {"title": "record player", "description": "vintage vinyl", "price": 149.99},
    {"title": "knives", "description": "stainless steel set", "price": 69.99},
    {"title": "blanket", "description": "bohemian fringe", "price": 39.99},
    {"title": "board", "description": "bamboo cutting", "price": 24.99},
    {"title": "dress", "description": "floral wrap", "price": 54.99},
    {"title": "stove", "description": "portable camping", "price": 49.99},
    {"title": "candles", "description": "artisanal scented", "price": 34.99},
    {"title": "bottle", "description": "stainless steel water", "price": 19.99},
    {"title": "dreamcatcher", "description": "boho chic", "price": 14.99},
    {"title": "sheets", "description": "organic bamboo", "price": 79.99},
    {"title": "journal", "description": "vintage leather", "price": 29.99},
    {"title": "lamp", "description": "himalayan salt", "price": 39.99},
    {"title": "camera", "description": "retro polaroid", "price": 89.99},
    {"title": "pillow", "description": "cozy knit throw", "price": 24.99},
    {"title": "press", "description": "stainless steel french", "price": 34.99},
    {"title": "plants", "description": "succulent assortment", "price": 19.99},
    {"title": "clock", "description": "minimalist geometric wall", "price": 39.99},
    {"title": "brushes", "description": "professional makeup", "price": 29.99},
    {"title": "teas", "description": "herbal sampler", "price": 14.99},
    {"title": "chess", "description": "wooden set", "price": 49.99},
    {"title": "diffuser", "description": "aromatherapy essential oil", "price": 29.99},
    {"title": "truffles", "description": "gourmet chocolate", "price": 24.99},
    {"title": "camera", "description": "smart home wi-fi security", "price": 69.99},
    {"title": "wallet", "description": "classic leather", "price": 34.99},
]